// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ofvutyqvdrodowdngzki.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9mdnV0eXF2ZHJvZG93ZG5nemtpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyNjU2MzgsImV4cCI6MjA3MTg0MTYzOH0.-Dwrd1qreEhDu9Eb5NiCX-10QlgwCW2tnqbGktWE-ko";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});